### ISSUE TITLE
Compile error on OSX

### ISSUE THREAD

**Issue by snayfach** [chenying2016/queries#1]
I encountered the following error when trying to compile on a MacBook Pro with OSX 10.9.4:

hs-blastn-0.0.3+-src$ make
MKDIR  objs/./sources/
  MKDIR  objs/./sources/commandline_options/
  MKDIR  objs/./sources/winmask/source/
  CC     sources/dbinfo.cpp => objs/./sources/dbinfo.o
  CC     sources/gapalign.cpp => objs/./sources/gapalign.o
sources/gapalign.cpp:326:61: warning: format specifies type 'long' but the
      argument has type 'Int8' (aka 'long long') [-Wformat]
  ...hsp->context, hsp->subject_id, hsp->q_off, hsp->q_end, hsp->s_off, hsp->...
                                                            ^~~~~~~~~~
sources/gapalign.cpp:326:73: warning: format specifies type 'long' but the
      argument has type 'Int8' (aka 'long long') [-Wformat]
  ...hsp->subject_id, hsp->q_off, hsp->q_end, hsp->s_off, hsp->s_end, hsp->sc...
                                                          ^~~~~~~~~~
2 warnings generated.
  CC     sources/greedy_align.cpp => objs/./sources/greedy_align.o
  CC     sources/index.cpp => objs/./sources/index.o
  CC     sources/interval_tree.cpp => objs/./sources/interval_tree.o
  CC     sources/line_reader.cpp => objs/./sources/line_reader.o
  CC     sources/main.cpp => objs/./sources/main.o
In file included from sources/main.cpp:2:
sources/thread_structure.h:14:5: error: unknown type name 'cpu_set_t'
    cpu_set_t mask;
    ^
1 error generated.
make: **\* [objs/./sources/main.o] Error 1

**Comment by chenying2016** [comment]
Dear snayfach:
    Thanks for your message. I have detected the same compiling problem on a MacBook Pro with OSX 10.10.3.
    To tackle this compiling problem, you may simply change the function in queries/hs-blastn-0.0.3+-src/sources/thread_structure.h (line 11):
 11 static inline int  
 12 BindCPU(int tid)  
 13 {  
 14     cpu_set_t mask;  
 15     CPU_ZERO(&mask);  
 16     CPU_SET(tid, &mask);  
 17     return pthread_setaffinity_np(pthread_self(), sizeof(mask), &mask);  
 18 }  
to
static inline int
BindCPU(int tid)
{
    return 0;
}

After this change, the source code compiles successfully on that MacBook.  I hope this will work for you. Enjoy!

Ying Chen

**Comment by snayfach** [comment]
Yes, it now compiles on OSX. In the future, would it be possible for your code to detect the platform (Linux or OSX) and compile accordingly? This way people won't need to make any changes to your code themselves. Thanks.
